library(robustbase)
library(ggplot2)
library(dlstats)
library(conjoint)
prefer <- read.csv("/Users/kyle/preferences.csv",header = T)
prof <- read.csv("/Users/kyle/profiles.csv",header = T)
imp <- caImportance (prefer, prof)
print("Importance summary: ", quote=FALSE)
print(imp)
